package tn.esprit.reactors;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.FontImage;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.FlowLayout;
import tn.esprit.reactors.chihab.forms.AssociationHomeForm;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
       /*Form associations = new Form(new FlowLayout(CENTER,CENTER));
       associations.add(new Label("Associations"));
       Form F2 = new Form(new FlowLayout(CENTER,CENTER));
       F2.add(new Label("Settings"));
       Form F3 = new Form(new FlowLayout(CENTER,CENTER));
       F3.add(new Label("About"));
       Form Home = new Form("Menu");
       Toolbar tb = Home.getToolbar();
       
       
     
       F2.getToolbar().addCommandToLeftBar("back", null,new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent evt) {
           Home.showBack();
           }
       });
       F3.getToolbar().addCommandToLeftBar("back", null,new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent evt) {
           Home.showBack();
           }
       });
       tb.addMaterialCommandToLeftSideMenu("Associations",FontImage.MATERIAL_WEB, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent evt) {
               AssociationHomeForm.getInstance(Home).showBack();
           }
       });
       tb.addMaterialCommandToLeftSideMenu("Settings",FontImage.MATERIAL_SETTINGS, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent evt) {
               F2.show();
           }
       });
       tb.addMaterialCommandToLeftSideMenu("About",FontImage.MATERIAL_INFO, new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent evt) {
               F3.show();
           }
       });
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        Home.show();*/
       
       new MyApplicationNasri().start();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
